Repository team-cobee/cobee-server, pull requests merged in 2025-09, with the labels that each got.

#51 [BE/CHORE] Dockerfile Gradle 빌드 권한 오류 다시 수정
  Dockerfile
Labels: ⚙️ chore, 💚 혜진

#75 [BE/REFACTOR] application.yml ddl-auto:create
  src/main/resources/application.yml
Labels: 🔨 refactoring, ❤️ 주연

#91 [Fix] corsConfiguration 수정
  src/main/java/org/cobee/server/config/SecurityConfig.java
Labels: :bug: fix, ❤️ 주연

#92 [BE/FIX] redirectURL 추가
  src/main/java/org/cobee/server/auth/handler/OAuth2AuthenticationSuccessHandler.java
Labels: :bug: fix, ❤️ 주연

#95 bugfix: chatroom 에서 내가 속한 채팅방 조회할 떄 lob 오류 해결 (#93)
  src/main/java/org/cobee/server/chat/repository/ChatRoomRepository.java
Labels: :bug: fix, 💚 혜진, 🐞bug

#97 [BE/REFACTOR] chatroom entity 수정
  src/main/java/org/cobee/server/chat/domain/ChatRoom.java
Labels: :bug: fix, 🔨 refactoring, 💚 혜진, 🐞bug

#107 [BE/Feat] 채팅방 기능 추가 _ 모집 완료 여부
  src/main/java/org/cobee/server/chat/controller/ChatRoomController.java
  src/main/java/org/cobee/server/chat/dto/ChatRoomCompleteResponseDto.java
  src/main/java/org/cobee/server/member/domain/Member.java
Labels: :bug: fix, 🔨 refactoring, :sparkles: feat, 💚 혜진, 🐞bug

#112 [FIX]ocr 비동기 + polling으로 수정
  src/main/java/org/cobee/server/global/error/code/ErrorCode.java
  src/main/java/org/cobee/server/ocr/controller/OcrController.java
  src/main/java/org/cobee/server/ocr/dto/OcrTask.java
  src/main/java/org/cobee/server/ocr/enums/OcrTaskStatus.java
  src/main/java/org/cobee/server/ocr/service/OcrService.java
Labels: :bug: fix, ❤️ 주연

#115 [BE/FIX] 환경 변수 main.yml 추가
  .github/workflows/main.yml
Labels: :bug: fix, ❤️ 주연, 🐞bug

#116 [BE/FIX] main.yml 수정
  .github/workflows/main.yml
Labels: :bug: fix, 🐞bug

#119 [BE/FIX] recruitPost 이미지 업로드 issue solve
  src/main/java/org/cobee/server/recruit/dto/RecruitResponse.java
Labels: :bug: fix, :sparkles: feat, ❤️ 주연, 🐞bug

#120 [BE/FIX] file 용량 최대치 update
  src/main/resources/application.yml
Labels: :bug: fix, ❤️ 주연, 🐞bug

#137 [BE/FIX] isComplete 반영
  src/main/java/org/cobee/server/member/domain/Member.java
  src/main/java/org/cobee/server/publicProfile/service/PublicProfileService.java
Labels: :bug: fix, :sparkles: feat, ❤️ 주연

#153 [BE/REFACTOR] 채팅방, 채팅 삭제 기능 추가
  src/main/java/org/cobee/server/auth/controller/AuthController.java
  src/main/java/org/cobee/server/chat/controller/ChatRoomController.java
  src/main/java/org/cobee/server/chat/document/ChatMessage.java
  src/main/java/org/cobee/server/chat/service/ChatService.java
Labels: 🔨 refactoring, 💚 혜진

#155 [BE/FEAT] add publicProfileById
  src/main/java/org/cobee/server/member/repository/MemberRepository.java
  src/main/java/org/cobee/server/publicProfile/controller/PublicProfileController.java
  src/main/java/org/cobee/server/publicProfile/service/PublicProfileService.java
  src/main/java/org/cobee/server/recruit/controller/RecruitController.java
  src/main/java/org/cobee/server/recruit/service/RecruitService.java
Labels: :sparkles: feat

#156 [BE/FIX] 지원자 초기화
  src/main/java/org/cobee/server/recruit/dto/RecruitResponse.java
Labels: :bug: fix, ❤️ 주연

#160 [BE/FIX] ocr api
  src/main/java/org/cobee/server/ocr/service/OcrService.java
Labels: :bug: fix, ❤️ 주연
